In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr1 = np.arange(0,11)

In [5]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr1[8]

8

In [9]:
arr1[1:5]

array([1, 2, 3, 4])

In [10]:
arr1[0:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[0:3] = 100

In [12]:
arr

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [13]:
arr = np.arange(0,11)

In [14]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_array = arr[0:6]

In [16]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_array[:] = 100

In [18]:
slice_of_array

array([100, 100, 100, 100, 100, 100])

In [19]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [26]:
arr_2nd = np.array(([5,15,20],[25,30,35],[40,45,50]))

In [27]:
arr_2nd

array([[ 5, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [29]:
arr_2nd[0]

array([ 5, 15, 20])

In [30]:
arr_2nd[1]

array([25, 30, 35])

In [31]:
arr_2nd[1][2]

35

In [33]:
arr_2nd[:2,1:]

array([[15, 20],
       [30, 35]])

In [35]:
arr2d = np.zeros([10,10])

In [36]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
arr_len = arr2d.shape[1]

In [40]:
arr_len

10

In [42]:
for i in range(arr_len):
    arr2d[i] = 1

In [43]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])